service: prepper-http-endpoints

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs12.x

functions:
  addToNewsletter:
    handler: server/handler.addToNewsletter
    events:
      - http:
          path: newletter
          method: post